addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-amazonlinux
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-debian-10
  - INSTANCE=default-fedora-latest
  - INSTANCE=default-opensuse-leap-15
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1804
  - INSTANCE=create-amazonlinux
  - INSTANCE=create-centos-6
  - INSTANCE=create-centos-7
  - INSTANCE=create-centos-8
  - INSTANCE=create-debian-9
  - INSTANCE=create-debian-10
  - INSTANCE=create-fedora-latest
  - INSTANCE=create-opensuse-leap-15
  - INSTANCE=create-ubuntu-1604
  - INSTANCE=create-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}
