dist: xenial
addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=installation-script-main-ubuntu-1604
  - INSTANCE=installation-script-main-ubuntu-1804
  - INSTANCE=installation-tarball-ubuntu-1604
  - INSTANCE=installation-tarball-ubuntu-1804
  - INSTANCE=installation-package-ubuntu-1604
  - INSTANCE=installation-package-ubuntu-1804
  - INSTANCE=registry-ubuntu-1804
  - INSTANCE=network-ubuntu-1804
  - INSTANCE=volume-ubuntu-1804
  - INSTANCE=resources-debian-9
  - INSTANCE=resources-debian-10
  - INSTANCE=resources-centos-7
  - INSTANCE=resources-fedora-latest
  - INSTANCE=resources-ubuntu-1604
  - INSTANCE=resources-ubuntu-1804

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: kitchen verify ${INSTANCE}
