name 'docker_compose_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docker_compose_test'
long_description 'Installs/Configures docker_compose_test'
version '0.1.1'

depends 'docker'
depends 'docker_compose'