sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=resources-ubuntu-1604
  - INSTANCE=resources-ubuntu-1804
  - INSTANCE=resources-debian-8
  - INSTANCE=resources-debian-9
  - INSTANCE=resources-centos-6
  - INSTANCE=resources-centos-7
  - INSTANCE=resources-fedora-latest
  - INSTANCE=resources-opensuse-leap
  - INSTANCE=source-ubuntu-1604
  - INSTANCE=source-ubuntu-1804
  - INSTANCE=source-debian-8
  - INSTANCE=source-debian-9
  - INSTANCE=source-centos-6
  - INSTANCE=source-centos-7
  - INSTANCE=source-fedora-latest
  - INSTANCE=source-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
