name              'yum-erlang_solutions'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures yum-erlang_solutions'
version           '2.1.4'
source_url        'https://github.com/sous-chefs/yum-erlang_solutions'
issues_url        'https://github.com/sous-chefs/yum-erlang_solutions/issues'
chef_version      '>= 12.15'

depends 'yum-epel'

supports 'amazon'
supports 'centos'
supports 'oracle'
supports 'redhat'
supports 'scientific'
