driver:
  name: <%= ENV['KI_DRIVER'] || 'vagrant' %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  install_strategy: <%= ENV['KI_INSTALL_STRATEGY'] || 'once' %>
  chef_license: accept-no-persist

transport:
  name: "ssh"

platforms:
  - name: centos-8
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: debian-10
  - name: fedora-34
  - name: opensuse-leap-15

#
# Suites
#

suites:
  - name: default-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugins]
      - recipe[rabbitmq::management_ui]
      - recipe[rabbitmq::vhosts]
      - recipe[rabbitmq::users]
      - recipe[rabbitmq::policies]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
        virtualhosts:
          - vhost1
          - vhost2
        enabled_users:
          - name: user1
            password: user1-pwd
            tag: management
            rights:
              - vhost: vhost1
                read: ".*"
                write: ".*"
                conf: ".*"
          - name: user2
            password: user2-pwd
            tag: management
            rights:
              - vhost: vhost2
                read: ".*"
                write: ".*"
                conf: ".*"
        policies:
          mirroring:
            pattern: "^mirrored\\."
            params:
              ha-mode: exactly
              ha-params: 2
            priority: 1
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["ubuntu-20.04", "ubuntu-18.04", "debian-10"]

  - name: management-plugin-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::management_ui]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/management_plugin
    includes: ["ubuntu-18.04"]

  - name: system-limits-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
        systemd:
          limits:
            NOFILE: 54000
    verifier:
      inspec_tests:
        - test/integration/limits
    includes: ["ubuntu-20.04", "ubuntu-18.04", "debian-10"]

  - name: use-distro-version-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
      - recipe[rabbitmq::management_ui]
      - recipe[rabbitmq::vhosts]
      - recipe[rabbitmq::users]
      - recipe[rabbitmq::policies]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:20.3.8.26-1"
      rabbitmq:
        use_distro_version: true
        virtualhosts:
          - vhost1
          - vhost2
        enabled_users:
          - name: user1
            password: user1-pwd
            tag: management
            rights:
              - vhost: vhost1
                read: ".*"
                write: ".*"
                conf: ".*"
          - name: user2
            password: user2-pwd
            tag: management
            rights:
              - vhost: vhost2
                read: ".*"
                write: ".*"
                conf: ".*"
        policies:
          mirroring:
            pattern: "^mirrored\\."
            params:
              ha-mode: exactly
              ha-params: 2
            priority: 2
          dlx:
            pattern: "^dlx\\."
            params:
              dead-letter-exchange: deadlettered
            priority: 1
    verifier:
      inspec_tests:
        - test/integration/36x
    includes: ["ubuntu-18.04"]

  - name: default-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["centos-8"]

  - name: default-modern-rpm
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::plugins]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "24.0.2"
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["centos-8", "fedora-34"]


  - name: system-limits-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::systemd_limits]
      - recipe[rabbitmq::plugins]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "24.0.2-1"
      rabbitmq:
        version: "3.8.17"
        systemd:
          limits:
            NOFILE: 54000
    verifier:
      inspec_tests:
        - test/integration/limits
    includes: ["centos-7"]

  - name: lwrps
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::lwrps]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/lwrps
    includes: ["ubuntu-18.04"]

  - name: cluster-deb
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cluster
    includes: ["ubuntu-18.04", "debian-10"]

  - name: cluster-rpm
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq_test::cluster]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/cluster
    includes: ["centos-7"]

  - name: default-force-yes
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    attributes:
      apt:
        confd:
          assume_yes: true
          force-yes: true
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["debian-10"]

  - name: default-force-yes-false
    run_list:
      - recipe[erlang::default]
      - recipe[rabbitmq::default]
    attributes:
      apt:
        confd:
          assume_yes: false
          force-yes: false
      erlang:
        install_method: "esl"
        esl:
          version: "1:24.0.2-1"
      rabbitmq:
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/integration/default
    includes: ["debian-10"]

  #
  # Team RabbitMQ Erlang packages
  #

  # Latest Erlang package, Debian
  - name: rabbitmq-erlang-latest-deb
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      # relies on node.rabbitmq.erlang.version default
      # which is nil/"install latest"
      rabbitmq:
        erlang:
          enabled: true
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_deb
    includes: ["debian-10", "ubuntu-18.04"]

  # Erlang package, Debian, version pinning
  - name: rabbitmq-erlang-pinned-deb
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "1:22.3.4.10.10-1"
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/erlang_package/pinned_deb
    includes: ["ubuntu-18.04"]

  # Latest Erlang package, RPM
  - name: rabbitmq-erlang-latest-rpm-el8
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      # relies on node.rabbitmq.erlang.version default
      # which is nil/"install latest"
      rabbitmq:
        erlang:
          enabled: true
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_rpm
    includes: ["fedora-34", "centos-8"]

  # Erlang package, RPM, version pinning
  - name: rabbitmq-erlang-pinned-rpm-el8
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
      rabbitmq:
        erlang:
          enabled: true
          version: "23.3"
          yum:
            baseurl: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/rpm/el/8/noarch
            repo_gpgcheck: true
        version: "3.8.17"
    verifier:
      inspec_tests:
        - test/erlang_package/pinned_rpm
    includes: ["fedora-34", "centos-8"]

  # Latest Erlang package, RPM, openSUSE leap 15 repo
  - name: rabbitmq-erlang-latest-rpm-suse
    run_list:
      - recipe[rabbitmq::erlang_package]
      - recipe[rabbitmq::default]
    attributes:
        rabbitmq:
          erlang:
            enabled: true
            zypper:
              baseurl: https://download.opensuse.org/repositories/network:/messaging:/amqp/openSUSE_Leap_15.1
          version: "3.8.17"
    verifier:
      inspec_tests:
        - test/erlang_package/latest_rpm
    includes: ["opensuse-leap-15"]
