sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
    #  - INSTANCE=default-amazonlinux # package install times out
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-9
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
    #- INSTANCE=canonical-amazonlinux
  - INSTANCE=canonical-centos-6
  - INSTANCE=canonical-centos-7
  - INSTANCE=canonical-debian-8
  - INSTANCE=canonical-debian-9
  - INSTANCE=canonical-ubuntu-1404
  - INSTANCE=canonical-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
    
