source 'https://rubygems.org'

gem 'rake'
gem 'minitest'

# version locking to support Ruby v2.1.4
gem 'foodcritic' # foodcritic 8.0+ drops support
gem 'rack'       # rack 2.0+ drops support

# allow CI to override the version of Chef for matrix testing
gem 'chef', (ENV['CHEF_VERSION'] || '12.1.0')

group :integration do
  gem 'berkshelf' # berkshelf 5.0+ drops support for Ruby <2.2
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
end
