source 'https://rubygrems.org'

gem 'berkshelf', '~> 6.3'
gem 'chef', '~> 13.6'
gem 'chefspec', '~> 7.1'
gem 'foodcritic', '~> 12.2'
gem 'rake', '~> 13.3'
gem 'rubocop', '~> 0.52'
gem 'stove', '~> 6.0'
