dist: trusty
sudo: false
cache: bundler
language: ruby
env:
  global:
    - secure: j4GV/0NXC6p/+XxgK2isMCzccR7ry8cxLJZZbJN5P+958lLGmYtPPsfAN+aRzcR3Uc/alLcsjXvceCjJWU7qYpkN1x9cn564J1X3OIOygi6xdYQIMLL5Guxp01QYabFlrmZeUnTVMTkdR1H4aRrpzW4kTuc5hbIZaJl0enEe1Dd+vbCw2GOTXFnPTeLDCaCSNXXhXmqqWD64leFR2PTwx8fwrXyCB/bDRXhFdsFA5Q/tCGW7PDaYujbqSCegpuz+uvHoM5S2k2XY3pShWZm9WcmEzCLEfhOGCc1s+ia7TZ0iV7kzEq11mNTdSl6nJtBUiKsgqw1TRPFhhUj2Bp/K+cNsd06rtFE3In2zbqbgyJ0qnyQHs2FZO//ve8bug+B0lA3i6SantruS1Fc9NjwjqzOmqmaqNhnVl1jEQTOB3JUC465QShySF0aJtjE5khD7PzGwCw6cqhPBLH5ZTmqCYvl/egYLMlvVr1Nboa+0YFdzUqoTFJpRTsu89l8+1+Eu9pvHn0CwsjWmEVHahIw/GEBjhLPDinquJNxWz1q49ozlohntbRmWhbgzz6D4wPrbBdyW7rYm8p6d2sOy6Op2zsVv4c7Dj3pcLLd9J5o6RaNxf4wLd5VFLNJR6/wldsZXGxV/iP16oyasabYIQYZNbP0U1hZiUpLQ5cvKYc6xRTM=
before_install:
  - 'if [[ $BUNDLE_GEMFILE == *master.gemfile ]]; then gem update --system; fi'
  - gem --version
  - gem install bundler
  - bundle --version
  - 'bundle config --local path ${BUNDLE_PATH:-$(dirname $BUNDLE_GEMFILE)/vendor/bundle}'
  - bundle config --local bin $PWD/bin
install: bundle update --jobs=3 --retry=3
script:
  - ./bin/rake travis
matrix:
  include:
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/master.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.16.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.17.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.18.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.19.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.20.gemfile
    - rvm: 2.3.1
      gemfile: test/gemfiles/chef-12.21.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.0.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.1.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.2.gemfile
    - rvm: 2.4.1
      gemfile: test/gemfiles/chef-13.3.gemfile
    - rvm: 2.4.2
      gemfile: test/gemfiles/chef-13.4.gemfile
    - rvm: 2.4.2
      gemfile: test/gemfiles/chef-13.5.gemfile
    - rvm: 2.4.2
      gemfile: test/gemfiles/chef-13.6.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.8.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.9.gemfile
    - rvm: 2.4.3
      gemfile: test/gemfiles/chef-13.10.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.0.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.1.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.2.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.3.gemfile
    - rvm: 2.5.1
      gemfile: test/gemfiles/chef-14.4.gemfile
